// <auto-generated />
using System;
using Cards_Products_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cards_Products_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251026201237_purchaseDetailEnPurchase")]
    partial class purchaseDetailEnPurchase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Cards_Products_API.Models.Card", b =>
                {
                    b.Property<int>("Card_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Card_Id"));

                    b.Property<string>("Card_Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Card_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Expiration_Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Card_Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Cards_Products_API.Models.Product", b =>
                {
                    b.Property<int>("Product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Product_Id"));

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Product_Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Cards_Products_API.Models.Purchase", b =>
                {
                    b.Property<int>("Purchase_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Purchase_Id"));

                    b.Property<int>("Card_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Purchase_Detail_Id")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Purchase_Id");

                    b.HasIndex("Card_Id");

                    b.HasIndex("Purchase_Detail_Id");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Cards_Products_API.Models.PurchaseDetail", b =>
                {
                    b.Property<int>("Purchase_Detail_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Purchase_Detail_Id"));

                    b.Property<int>("Product_Id")
                        .HasColumnType("int");

                    b.Property<int>("Purchase_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SubTotal")
                        .HasColumnType("int");

                    b.HasKey("Purchase_Detail_Id");

                    b.HasIndex("Product_Id");

                    b.HasIndex("Purchase_Id");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("Cards_Products_API.Models.Purchase", b =>
                {
                    b.HasOne("Cards_Products_API.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("Card_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cards_Products_API.Models.PurchaseDetail", "PurchaseDetail")
                        .WithMany()
                        .HasForeignKey("Purchase_Detail_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("PurchaseDetail");
                });

            modelBuilder.Entity("Cards_Products_API.Models.PurchaseDetail", b =>
                {
                    b.HasOne("Cards_Products_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cards_Products_API.Models.Purchase", "Purchase")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("Purchase_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Cards_Products_API.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
